/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package assignment3_order;

import javax.swing.JOptionPane;

/**
 *
 * @author senafunakubo
 */
public class Order extends javax.swing.JFrame {

//    Price price = null;
    Price sushiPrice = new Price(0,0,0);
    /**
     * Creates new form Order
     */
    public Order() {
         
        initComponents();
        setLocationRelativeTo(null);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new javax.swing.JPanel();
        SushiPageLabel = new javax.swing.JLabel();
        UserInfoPageLabel = new javax.swing.JLabel();
        PaymentPageLabel = new javax.swing.JLabel();
        SushiBaiPicLabel = new javax.swing.JLabel();
        SushiChikuPicLabel = new javax.swing.JLabel();
        SushiSyoPicLabel = new javax.swing.JLabel();
        SushiSyoNameLabel = new javax.swing.JLabel();
        SushiChikuNameLabel = new javax.swing.JLabel();
        SushiBaiNameLabel = new javax.swing.JLabel();
        SushiBaiExplaLabel = new javax.swing.JLabel();
        SushiChikuExplaLabel = new javax.swing.JLabel();
        SushiSyoExplaLabel = new javax.swing.JLabel();
        SushiSyoExplaLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Plus = new javax.swing.JButton();
        Plus2 = new javax.swing.JButton();
        Minus = new javax.swing.JButton();
        Minus3 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        Minus2 = new javax.swing.JButton();
        Plus3 = new javax.swing.JButton();
        AddCartButton = new javax.swing.JButton();
        ResetButton = new javax.swing.JButton();
        BluePanel = new javax.swing.JPanel();
        TotalLabel = new javax.swing.JLabel();
        PriceLabel = new javax.swing.JLabel();
        BlueChikuLabel = new javax.swing.JLabel();
        BlueSyoLabel = new javax.swing.JLabel();
        BlueBaiLabel = new javax.swing.JLabel();
        BlueSyoPriceLabel = new javax.swing.JLabel();
        BlueChikuPriceLabel = new javax.swing.JLabel();
        BlueBaiPriceLabel = new javax.swing.JLabel();
        ShoppingCartLabel = new javax.swing.JLabel();
        CheckOut = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        MainPanel.setBackground(new java.awt.Color(251, 251, 251));
        MainPanel.setPreferredSize(new java.awt.Dimension(690, 446));

        SushiPageLabel.setFont(new java.awt.Font("Tsukushi B Round Gothic", 2, 14)); // NOI18N
        SushiPageLabel.setForeground(new java.awt.Color(51, 51, 51));
        SushiPageLabel.setText("Sushi");
        SushiPageLabel.setPreferredSize(new java.awt.Dimension(34, 24));

        UserInfoPageLabel.setFont(new java.awt.Font("Tsukushi B Round Gothic", 0, 14)); // NOI18N
        UserInfoPageLabel.setForeground(new java.awt.Color(204, 204, 204));
        UserInfoPageLabel.setText("UserInfo");

        PaymentPageLabel.setFont(new java.awt.Font("Tsukushi B Round Gothic", 0, 14)); // NOI18N
        PaymentPageLabel.setForeground(new java.awt.Color(204, 204, 204));
        PaymentPageLabel.setText("Payment");

        SushiBaiPicLabel.setIcon(new javax.swing.ImageIcon("/Users/senafunakubo/Downloads/s_sushi_sho.png")); // NOI18N

        SushiChikuPicLabel.setIcon(new javax.swing.ImageIcon("/Users/senafunakubo/Downloads/s_sushi_chiku.jpg")); // NOI18N

        SushiSyoPicLabel.setIcon(new javax.swing.ImageIcon("/Users/senafunakubo/Downloads/s_sushi_bai.jpg")); // NOI18N

        SushiSyoNameLabel.setFont(new java.awt.Font("Tsukushi B Round Gothic", 3, 13)); // NOI18N
        SushiSyoNameLabel.setForeground(new java.awt.Color(0, 153, 153));
        SushiSyoNameLabel.setText("Syo(松)");
        SushiSyoNameLabel.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(51, 51, 51)));

        SushiChikuNameLabel.setFont(new java.awt.Font("Tsukushi B Round Gothic", 3, 13)); // NOI18N
        SushiChikuNameLabel.setForeground(new java.awt.Color(0, 153, 153));
        SushiChikuNameLabel.setText("Chiku(竹)");
        SushiChikuNameLabel.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(51, 51, 51)));

        SushiBaiNameLabel.setFont(new java.awt.Font("Tsukushi B Round Gothic", 3, 13)); // NOI18N
        SushiBaiNameLabel.setForeground(new java.awt.Color(0, 153, 153));
        SushiBaiNameLabel.setText("Bai(梅)");
        SushiBaiNameLabel.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(51, 51, 51)));

        SushiBaiExplaLabel.setFont(new java.awt.Font("Tsukushi A Round Gothic", 0, 12)); // NOI18N
        SushiBaiExplaLabel.setForeground(new java.awt.Color(51, 51, 51));
        SushiBaiExplaLabel.setText("Alaska roll ( 6 pieces )");

        SushiChikuExplaLabel.setFont(new java.awt.Font("Tsukushi A Round Gothic", 0, 12)); // NOI18N
        SushiChikuExplaLabel.setForeground(new java.awt.Color(51, 51, 51));
        SushiChikuExplaLabel.setText("Omakase nigiri ( 10 pieces )");

        SushiSyoExplaLabel.setFont(new java.awt.Font("Tsukushi A Round Gothic", 0, 12)); // NOI18N
        SushiSyoExplaLabel.setForeground(new java.awt.Color(51, 51, 51));
        SushiSyoExplaLabel.setText("Party nigiri + rolls + Sashimi");

        SushiSyoExplaLabel2.setFont(new java.awt.Font("Tsukushi A Round Gothic", 0, 12)); // NOI18N
        SushiSyoExplaLabel2.setForeground(new java.awt.Color(51, 51, 51));
        SushiSyoExplaLabel2.setText(" ( 34 pieces )");

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator1.setForeground(new java.awt.Color(51, 51, 51));

        jLabel1.setFont(new java.awt.Font("Tsukushi B Round Gothic", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("                                           $39");
        jLabel1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(51, 51, 51)));

        jLabel2.setFont(new java.awt.Font("Tsukushi B Round Gothic", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("                                            $15");
        jLabel2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(51, 51, 51)));

        jLabel3.setFont(new java.awt.Font("Tsukushi B Round Gothic", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("                                             $9");
        jLabel3.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(51, 51, 51)));

        Plus.setForeground(new java.awt.Color(51, 51, 51));
        Plus.setText("+");
        Plus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PlusMouseClicked(evt);
            }
        });
        Plus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlusActionPerformed(evt);
            }
        });

        Plus2.setText("+");
        Plus2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Plus2MouseClicked(evt);
            }
        });
        Plus2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Plus2ActionPerformed(evt);
            }
        });

        Minus.setText("-");
        Minus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MinusMouseClicked(evt);
            }
        });
        Minus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MinusActionPerformed(evt);
            }
        });

        Minus3.setText("-");
        Minus3.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                Minus3ComponentAdded(evt);
            }
        });
        Minus3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Minus3MouseClicked(evt);
            }
        });
        Minus3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Minus3ActionPerformed(evt);
            }
        });

        jTextField1.setText("0");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jTextField2.setText("0");
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jTextField3.setText("0");
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        Minus2.setText("-");
        Minus2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Minus2MouseClicked(evt);
            }
        });
        Minus2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Minus2ActionPerformed(evt);
            }
        });

        Plus3.setText("+");
        Plus3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Plus3MouseClicked(evt);
            }
        });
        Plus3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Plus3ActionPerformed(evt);
            }
        });

        AddCartButton.setBackground(new java.awt.Color(51, 51, 51));
        AddCartButton.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        AddCartButton.setForeground(new java.awt.Color(255, 255, 255));
        AddCartButton.setText("Add to cart");
        AddCartButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddCartButtonMouseClicked(evt);
            }
        });
        AddCartButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddCartButtonActionPerformed(evt);
            }
        });

        ResetButton.setBackground(new java.awt.Color(251, 251, 251));
        ResetButton.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        ResetButton.setForeground(new java.awt.Color(51, 51, 51));
        ResetButton.setText("Reset");
        ResetButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ResetButtonMouseClicked(evt);
            }
        });
        ResetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MainPanelLayout = new javax.swing.GroupLayout(MainPanel);
        MainPanel.setLayout(MainPanelLayout);
        MainPanelLayout.setHorizontalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(SushiSyoExplaLabel2)
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(MainPanelLayout.createSequentialGroup()
                                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, MainPanelLayout.createSequentialGroup()
                                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Plus, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Minus, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(SushiSyoExplaLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(SushiSyoNameLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(SushiPageLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(SushiSyoPicLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(60, 60, 60)
                                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(SushiChikuExplaLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(SushiChikuPicLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(SushiChikuNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(UserInfoPageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(MainPanelLayout.createSequentialGroup()
                                        .addGap(65, 65, 65)
                                        .addComponent(Plus2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Minus2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(ResetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainPanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                                .addComponent(PaymentPageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(MainPanelLayout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(AddCartButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(SushiBaiNameLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(SushiBaiPicLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(SushiBaiExplaLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, MainPanelLayout.createSequentialGroup()
                                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Plus3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Minus3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addComponent(jSeparator1))
                .addGap(60, 60, 60))
        );
        MainPanelLayout.setVerticalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(UserInfoPageLabel)
                    .addComponent(SushiPageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PaymentPageLabel))
                .addGap(0, 0, 0)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(SushiSyoPicLabel)
                    .addComponent(SushiChikuPicLabel)
                    .addComponent(SushiBaiPicLabel))
                .addGap(15, 15, 15)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(SushiSyoNameLabel)
                    .addComponent(SushiChikuNameLabel)
                    .addComponent(SushiBaiNameLabel))
                .addGap(10, 10, 10)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SushiSyoExplaLabel)
                    .addComponent(SushiChikuExplaLabel)
                    .addComponent(SushiBaiExplaLabel))
                .addComponent(SushiSyoExplaLabel2)
                .addGap(8, 8, 8)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(15, 15, 15)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Plus, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Minus, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Plus3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Minus2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Plus2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Minus3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddCartButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ResetButton))
                .addGap(40, 40, 40))
        );

        MainPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {SushiBaiPicLabel, SushiChikuPicLabel, SushiSyoPicLabel});

        BluePanel.setBackground(new java.awt.Color(0, 153, 153));
        BluePanel.setForeground(new java.awt.Color(59, 175, 235));

        TotalLabel.setFont(new java.awt.Font("Tsukushi A Round Gothic", 1, 10)); // NOI18N
        TotalLabel.setForeground(new java.awt.Color(255, 255, 255));
        TotalLabel.setText("Total");

        PriceLabel.setFont(new java.awt.Font("Tsukushi A Round Gothic", 1, 10)); // NOI18N
        PriceLabel.setForeground(new java.awt.Color(255, 255, 255));
        PriceLabel.setText("$0");

        BlueChikuLabel.setFont(new java.awt.Font("Tsukushi A Round Gothic", 0, 10)); // NOI18N
        BlueChikuLabel.setForeground(new java.awt.Color(255, 255, 255));
        BlueChikuLabel.setText("Chiku");

        BlueSyoLabel.setFont(new java.awt.Font("Tsukushi A Round Gothic", 0, 10)); // NOI18N
        BlueSyoLabel.setForeground(new java.awt.Color(255, 255, 255));
        BlueSyoLabel.setText("Syo");

        BlueBaiLabel.setFont(new java.awt.Font("Tsukushi A Round Gothic", 0, 10)); // NOI18N
        BlueBaiLabel.setForeground(new java.awt.Color(255, 255, 255));
        BlueBaiLabel.setText("Bai");

        BlueSyoPriceLabel.setFont(new java.awt.Font("Tsukushi A Round Gothic", 0, 10)); // NOI18N
        BlueSyoPriceLabel.setForeground(new java.awt.Color(255, 255, 255));
        BlueSyoPriceLabel.setText("$0");

        BlueChikuPriceLabel.setFont(new java.awt.Font("Tsukushi A Round Gothic", 0, 10)); // NOI18N
        BlueChikuPriceLabel.setForeground(new java.awt.Color(255, 255, 255));
        BlueChikuPriceLabel.setText("$0");

        BlueBaiPriceLabel.setFont(new java.awt.Font("Tsukushi A Round Gothic", 0, 10)); // NOI18N
        BlueBaiPriceLabel.setForeground(new java.awt.Color(255, 255, 255));
        BlueBaiPriceLabel.setText("$0");

        ShoppingCartLabel.setFont(new java.awt.Font("Tsukushi B Round Gothic", 0, 14)); // NOI18N
        ShoppingCartLabel.setForeground(new java.awt.Color(255, 255, 255));
        ShoppingCartLabel.setText("Shopping Cart");

        CheckOut.setBackground(new java.awt.Color(0, 153, 153));
        CheckOut.setForeground(new java.awt.Color(251, 251, 251));
        CheckOut.setText("CheckOut");
        CheckOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CheckOutMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout BluePanelLayout = new javax.swing.GroupLayout(BluePanel);
        BluePanel.setLayout(BluePanelLayout);
        BluePanelLayout.setHorizontalGroup(
            BluePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BluePanelLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(BluePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ShoppingCartLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BluePanelLayout.createSequentialGroup()
                        .addGroup(BluePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(BluePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BluePanelLayout.createSequentialGroup()
                                    .addComponent(BlueSyoLabel)
                                    .addGap(12, 12, 12))
                                .addComponent(BlueChikuLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BluePanelLayout.createSequentialGroup()
                                    .addComponent(BlueBaiLabel)
                                    .addGap(14, 14, 14)))
                            .addComponent(TotalLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(BluePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BlueSyoPriceLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(BlueChikuPriceLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(BlueBaiPriceLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(PriceLabel, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addComponent(CheckOut, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(45, 45, 45))
        );
        BluePanelLayout.setVerticalGroup(
            BluePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BluePanelLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(ShoppingCartLabel)
                .addGap(52, 52, 52)
                .addGroup(BluePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BlueSyoLabel)
                    .addComponent(BlueSyoPriceLabel))
                .addGap(18, 18, 18)
                .addGroup(BluePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BlueChikuLabel)
                    .addComponent(BlueChikuPriceLabel))
                .addGap(18, 18, 18)
                .addGroup(BluePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BlueBaiLabel)
                    .addComponent(BlueBaiPriceLabel))
                .addGap(99, 99, 99)
                .addGroup(BluePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PriceLabel)
                    .addComponent(TotalLabel))
                .addGap(27, 27, 27)
                .addComponent(CheckOut, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(BluePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BluePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void Minus3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Minus3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Minus3ActionPerformed

    private void Plus2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Plus2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Plus2ActionPerformed

    private void PlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PlusActionPerformed

    private void MinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MinusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MinusActionPerformed

    private void PlusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PlusMouseClicked
        // TODO add your handling code here:
        String text = jTextField1.getText();
        int count = Integer.parseInt(text);
        if(count>=0 && count<10){
         count++;
        }
        String st1 = Integer.toString(count);
        jTextField1.setText(st1);
    }//GEN-LAST:event_PlusMouseClicked

    private void Minus2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Minus2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Minus2ActionPerformed

    private void Plus3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Plus3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Plus3ActionPerformed

    private void MinusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinusMouseClicked
        // TODO add your handling code here:
        String text = jTextField1.getText();
        int count = Integer.parseInt(text);
        if(count>=1 && count<11){
         count--;
        }
        String st1 = Integer.toString(count);
        jTextField1.setText(st1);
    }//GEN-LAST:event_MinusMouseClicked

    private void Plus2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Plus2MouseClicked
        // TODO add your handling code here:
        String text = jTextField2.getText();
        int count = Integer.parseInt(text);
        if(count>=0 && count<10){
         count++;
        }
        String st1 = Integer.toString(count);
        jTextField2.setText(st1);
    }//GEN-LAST:event_Plus2MouseClicked

    private void Minus2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Minus2MouseClicked
        // TODO add your handling code here:
        String text = jTextField2.getText();
        int count = Integer.parseInt(text);
        if(count>=1 && count<11){
         count--;
        }
        String st1 = Integer.toString(count);
        jTextField2.setText(st1);
    }//GEN-LAST:event_Minus2MouseClicked

    private void Plus3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Plus3MouseClicked
        // TODO add your handling code here:
        String text = jTextField3.getText();
        int count = Integer.parseInt(text);
        if(count>=0 && count<10){
         count++;
        }
        String st1 = Integer.toString(count);
        jTextField3.setText(st1);
    }//GEN-LAST:event_Plus3MouseClicked

    private void Minus3ComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_Minus3ComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_Minus3ComponentAdded

    private void Minus3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Minus3MouseClicked
        // TODO add your handling code here:
        String text = jTextField3.getText();
        int count = Integer.parseInt(text);
        if(count>=1 && count<11){
         count--;
        }
        String st1 = Integer.toString(count);
        jTextField3.setText(st1);
    }//GEN-LAST:event_Minus3MouseClicked

    private void AddCartButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddCartButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddCartButtonActionPerformed

    private void AddCartButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddCartButtonMouseClicked
        // TODO add your handling code here:
        
        //For calculate the sum of Syo
        String text = jTextField1.getText();
        int priceSyo = Integer.parseInt(text);
        int sum = priceSyo * 39;
        String result = Integer.toString(sum);
        BlueSyoPriceLabel.setText("$" + result);
        
        //For calculate the sum of Chiku
        String text2 = jTextField2.getText();
        int priceChiku = Integer.parseInt(text2);
        int sum2 = priceChiku * 15;
        String result2 = Integer.toString(sum2);
        BlueChikuPriceLabel.setText("$" + result2);
        
        //For calculate the sum of Bai
        String text3 = jTextField3.getText();
        int priceBai = Integer.parseInt(text3);
        int sum3 = priceBai * 9;
        String result3 = Integer.toString(sum3);
        BlueBaiPriceLabel.setText("$" + result3);
        
        //For calculate all the sum
        int allResult = sum + sum2 + sum3;
        String allSum = Integer.toString(allResult);
        PriceLabel.setText("$" + allSum);
        
        sushiPrice.setSyo(sum);
        sushiPrice.setChiku(sum2);
        sushiPrice.setBai(sum3);
        
    }//GEN-LAST:event_AddCartButtonMouseClicked

    private void ResetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ResetButtonActionPerformed

    private void ResetButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ResetButtonMouseClicked
        // TODO add your handling code here:
        jTextField1.setText("0");
        jTextField2.setText("0");
        jTextField3.setText("0");
        BlueSyoPriceLabel.setText("$0");
        BlueChikuPriceLabel.setText("$0");
        BlueBaiPriceLabel.setText("$0");
        PriceLabel.setText("$0");
    }//GEN-LAST:event_ResetButtonMouseClicked

    private void CheckOutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CheckOutMouseClicked
        // TODO add your handling code here:
        String cutSum = PriceLabel.getText().substring(1);
        int price = Integer.parseInt(cutSum);
        if(price>0){
          UserInfo infoPage= new UserInfo();
          infoPage.ShowShoppingCart(sushiPrice);
          infoPage.setVisible(true);
        }else{
          JOptionPane.showMessageDialog(null, "Please add more than one item.");
        }
    }//GEN-LAST:event_CheckOutMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Order().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddCartButton;
    private javax.swing.JLabel BlueBaiLabel;
    private javax.swing.JLabel BlueBaiPriceLabel;
    private javax.swing.JLabel BlueChikuLabel;
    private javax.swing.JLabel BlueChikuPriceLabel;
    private javax.swing.JPanel BluePanel;
    private javax.swing.JLabel BlueSyoLabel;
    private javax.swing.JLabel BlueSyoPriceLabel;
    private javax.swing.JButton CheckOut;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JButton Minus;
    private javax.swing.JButton Minus2;
    private javax.swing.JButton Minus3;
    private javax.swing.JLabel PaymentPageLabel;
    private javax.swing.JButton Plus;
    private javax.swing.JButton Plus2;
    private javax.swing.JButton Plus3;
    private javax.swing.JLabel PriceLabel;
    private javax.swing.JButton ResetButton;
    private javax.swing.JLabel ShoppingCartLabel;
    private javax.swing.JLabel SushiBaiExplaLabel;
    private javax.swing.JLabel SushiBaiNameLabel;
    private javax.swing.JLabel SushiBaiPicLabel;
    private javax.swing.JLabel SushiChikuExplaLabel;
    private javax.swing.JLabel SushiChikuNameLabel;
    private javax.swing.JLabel SushiChikuPicLabel;
    private javax.swing.JLabel SushiPageLabel;
    private javax.swing.JLabel SushiSyoExplaLabel;
    private javax.swing.JLabel SushiSyoExplaLabel2;
    private javax.swing.JLabel SushiSyoNameLabel;
    private javax.swing.JLabel SushiSyoPicLabel;
    private javax.swing.JLabel TotalLabel;
    private javax.swing.JLabel UserInfoPageLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
