/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package assignment3_order;

import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author senafunakubo
 */
public class UserInfo extends javax.swing.JFrame {
    User user = new User("","","",0,"","","");
    
    Connection connection = null;
    PreparedStatement pst = null;
    ResultSet resultSet = null;
    
    /** Creates new form UserInfo */
    public UserInfo() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new javax.swing.JPanel();
        SushiPageLabel = new javax.swing.JLabel();
        UserInfoPageLabel = new javax.swing.JLabel();
        PaymentPageLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        firstNameLabel = new javax.swing.JLabel();
        lastNameLabel = new javax.swing.JLabel();
        EmailLabel = new javax.swing.JLabel();
        firstNameTF = new javax.swing.JTextField();
        lastNameTF = new javax.swing.JTextField();
        EmailTF = new javax.swing.JTextField();
        phoneNumLabel = new javax.swing.JLabel();
        AddressLabel = new javax.swing.JLabel();
        PhoneNumTF = new javax.swing.JTextField();
        AddressTF = new javax.swing.JTextField();
        cityLabel = new javax.swing.JLabel();
        cityTF = new javax.swing.JTextField();
        zipCodeLabel = new javax.swing.JLabel();
        zipCodeTF = new javax.swing.JTextField();
        cancelButton = new javax.swing.JButton();
        RegisterButton = new javax.swing.JButton();
        alreadyMemberLabel = new javax.swing.JLabel();
        BluePanel = new javax.swing.JPanel();
        TotalLabel = new javax.swing.JLabel();
        PriceLabel = new javax.swing.JLabel();
        BlueChikuLabel = new javax.swing.JLabel();
        BlueSyoLabel = new javax.swing.JLabel();
        BlueBaiLabel = new javax.swing.JLabel();
        BlueSyoPriceLabel = new javax.swing.JLabel();
        BlueChikuPriceLabel = new javax.swing.JLabel();
        BlueBaiPriceLabel = new javax.swing.JLabel();
        ShoppingCartLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MainPanel.setBackground(new java.awt.Color(251, 251, 251));

        SushiPageLabel.setFont(new java.awt.Font("Tsukushi B Round Gothic", 0, 14)); // NOI18N
        SushiPageLabel.setForeground(new java.awt.Color(204, 204, 204));
        SushiPageLabel.setText("Sushi");
        SushiPageLabel.setPreferredSize(new java.awt.Dimension(34, 24));

        UserInfoPageLabel.setFont(new java.awt.Font("Tsukushi B Round Gothic", 2, 14)); // NOI18N
        UserInfoPageLabel.setForeground(new java.awt.Color(51, 51, 51));
        UserInfoPageLabel.setText("UserInfo");

        PaymentPageLabel.setFont(new java.awt.Font("Tsukushi B Round Gothic", 0, 14)); // NOI18N
        PaymentPageLabel.setForeground(new java.awt.Color(204, 204, 204));
        PaymentPageLabel.setText("Payment");

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator1.setForeground(new java.awt.Color(51, 51, 51));

        firstNameLabel.setFont(new java.awt.Font("Tsukushi A Round Gothic", 0, 10)); // NOI18N
        firstNameLabel.setText("First name");

        lastNameLabel.setFont(new java.awt.Font("Tsukushi A Round Gothic", 0, 10)); // NOI18N
        lastNameLabel.setText("Last name");

        EmailLabel.setFont(new java.awt.Font("Tsukushi A Round Gothic", 0, 10)); // NOI18N
        EmailLabel.setText("Email");

        firstNameTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstNameTFActionPerformed(evt);
            }
        });

        phoneNumLabel.setFont(new java.awt.Font("Tsukushi A Round Gothic", 0, 10)); // NOI18N
        phoneNumLabel.setText("Phone number");

        AddressLabel.setFont(new java.awt.Font("Tsukushi A Round Gothic", 0, 10)); // NOI18N
        AddressLabel.setText("Address");

        cityLabel.setFont(new java.awt.Font("Tsukushi A Round Gothic", 0, 10)); // NOI18N
        cityLabel.setText("City");

        zipCodeLabel.setFont(new java.awt.Font("Tsukushi A Round Gothic", 0, 10)); // NOI18N
        zipCodeLabel.setText("Zip code");

        cancelButton.setBackground(new java.awt.Color(251, 251, 251));
        cancelButton.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        cancelButton.setForeground(new java.awt.Color(51, 51, 51));
        cancelButton.setText("Cancel");
        cancelButton.setMaximumSize(new java.awt.Dimension(81, 29));
        cancelButton.setMinimumSize(new java.awt.Dimension(81, 29));
        cancelButton.setPreferredSize(new java.awt.Dimension(81, 29));
        cancelButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelButtonMouseClicked(evt);
            }
        });

        RegisterButton.setBackground(new java.awt.Color(0, 153, 153));
        RegisterButton.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        RegisterButton.setForeground(new java.awt.Color(251, 251, 251));
        RegisterButton.setText("Register");
        RegisterButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RegisterButtonMouseClicked(evt);
            }
        });

        alreadyMemberLabel.setFont(new java.awt.Font("Tsukushi A Round Gothic", 0, 12)); // NOI18N
        alreadyMemberLabel.setText("Already a member ");
        alreadyMemberLabel.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(51, 51, 51)));
        alreadyMemberLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                alreadyMemberLabelMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                alreadyMemberLabelMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                alreadyMemberLabelMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout MainPanelLayout = new javax.swing.GroupLayout(MainPanel);
        MainPanel.setLayout(MainPanelLayout);
        MainPanelLayout.setHorizontalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(MainPanelLayout.createSequentialGroup()
                                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(firstNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                        .addComponent(firstNameTF))
                                    .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(cityLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(cityTF, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(PhoneNumTF, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(phoneNumLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                        .addComponent(cancelButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(MainPanelLayout.createSequentialGroup()
                                        .addGap(60, 60, 60)
                                        .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(lastNameTF, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(AddressLabel, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(zipCodeLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(zipCodeTF, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lastNameLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(UserInfoPageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                                        .addGap(60, 60, 60)
                                        .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(EmailLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(EmailTF)))
                                    .addGroup(MainPanelLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(RegisterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(30, 30, 30)
                                        .addComponent(alreadyMemberLabel))))
                            .addGroup(MainPanelLayout.createSequentialGroup()
                                .addGap(210, 210, 210)
                                .addComponent(AddressTF)))
                        .addGap(60, 60, 60))
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SushiPageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(MainPanelLayout.createSequentialGroup()
                                .addGap(420, 420, 420)
                                .addComponent(PaymentPageLabel)))
                        .addGap(50, 50, 50))))
        );
        MainPanelLayout.setVerticalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(UserInfoPageLabel)
                    .addComponent(SushiPageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PaymentPageLabel))
                .addGap(0, 0, 0)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstNameLabel)
                    .addComponent(lastNameLabel)
                    .addComponent(EmailLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lastNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EmailTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(phoneNumLabel)
                    .addComponent(AddressLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PhoneNumTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddressTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cityLabel)
                    .addComponent(zipCodeLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cityTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(zipCodeTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RegisterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(alreadyMemberLabel))
                .addGap(40, 40, 40))
        );

        BluePanel.setBackground(new java.awt.Color(0, 153, 153));
        BluePanel.setForeground(new java.awt.Color(59, 175, 235));

        TotalLabel.setFont(new java.awt.Font("Tsukushi A Round Gothic", 1, 10)); // NOI18N
        TotalLabel.setForeground(new java.awt.Color(255, 255, 255));
        TotalLabel.setText("Total");

        PriceLabel.setFont(new java.awt.Font("Tsukushi A Round Gothic", 1, 10)); // NOI18N
        PriceLabel.setForeground(new java.awt.Color(255, 255, 255));
        PriceLabel.setText("$0");

        BlueChikuLabel.setFont(new java.awt.Font("Tsukushi A Round Gothic", 0, 10)); // NOI18N
        BlueChikuLabel.setForeground(new java.awt.Color(255, 255, 255));
        BlueChikuLabel.setText("Chiku");

        BlueSyoLabel.setFont(new java.awt.Font("Tsukushi A Round Gothic", 0, 10)); // NOI18N
        BlueSyoLabel.setForeground(new java.awt.Color(255, 255, 255));
        BlueSyoLabel.setText("Syo");

        BlueBaiLabel.setFont(new java.awt.Font("Tsukushi A Round Gothic", 0, 10)); // NOI18N
        BlueBaiLabel.setForeground(new java.awt.Color(255, 255, 255));
        BlueBaiLabel.setText("Bai");

        BlueSyoPriceLabel.setFont(new java.awt.Font("Tsukushi A Round Gothic", 0, 10)); // NOI18N
        BlueSyoPriceLabel.setForeground(new java.awt.Color(255, 255, 255));
        BlueSyoPriceLabel.setText("$0");

        BlueChikuPriceLabel.setFont(new java.awt.Font("Tsukushi A Round Gothic", 0, 10)); // NOI18N
        BlueChikuPriceLabel.setForeground(new java.awt.Color(255, 255, 255));
        BlueChikuPriceLabel.setText("$0");

        BlueBaiPriceLabel.setFont(new java.awt.Font("Tsukushi A Round Gothic", 0, 10)); // NOI18N
        BlueBaiPriceLabel.setForeground(new java.awt.Color(255, 255, 255));
        BlueBaiPriceLabel.setText("$0");

        ShoppingCartLabel.setFont(new java.awt.Font("Tsukushi B Round Gothic", 0, 14)); // NOI18N
        ShoppingCartLabel.setForeground(new java.awt.Color(255, 255, 255));
        ShoppingCartLabel.setText("Shopping Cart");

        javax.swing.GroupLayout BluePanelLayout = new javax.swing.GroupLayout(BluePanel);
        BluePanel.setLayout(BluePanelLayout);
        BluePanelLayout.setHorizontalGroup(
            BluePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BluePanelLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(BluePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ShoppingCartLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BluePanelLayout.createSequentialGroup()
                        .addGroup(BluePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(BluePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BluePanelLayout.createSequentialGroup()
                                    .addComponent(BlueSyoLabel)
                                    .addGap(12, 12, 12))
                                .addComponent(BlueChikuLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BluePanelLayout.createSequentialGroup()
                                    .addComponent(BlueBaiLabel)
                                    .addGap(14, 14, 14)))
                            .addComponent(TotalLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(BluePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BlueSyoPriceLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(BlueChikuPriceLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(BlueBaiPriceLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(PriceLabel, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGap(45, 45, 45))
        );
        BluePanelLayout.setVerticalGroup(
            BluePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BluePanelLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(ShoppingCartLabel)
                .addGap(52, 52, 52)
                .addGroup(BluePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BlueSyoLabel)
                    .addComponent(BlueSyoPriceLabel))
                .addGap(18, 18, 18)
                .addGroup(BluePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BlueChikuLabel)
                    .addComponent(BlueChikuPriceLabel))
                .addGap(18, 18, 18)
                .addGroup(BluePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BlueBaiLabel)
                    .addComponent(BlueBaiPriceLabel))
                .addGap(99, 99, 99)
                .addGroup(BluePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PriceLabel)
                    .addComponent(TotalLabel))
                .addContainerGap(189, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(BluePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BluePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void firstNameTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstNameTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstNameTFActionPerformed

    private void cancelButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelButtonMouseClicked
        // TODO add your handling code here:
        Order orderPage = new Order();
        orderPage.setVisible(true);
    }//GEN-LAST:event_cancelButtonMouseClicked

    private void RegisterButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegisterButtonMouseClicked
        // TODO add your handling code here:
        String firstName = firstNameTF.getText();
        String lastName = lastNameTF.getText();
        String email = EmailTF.getText();
        
        String phoneNum = PhoneNumTF.getText();
        int phoneNumIn = Integer.parseInt(phoneNum);
        
        String address = AddressTF.getText();
        String city = cityTF.getText();
        String zipCode = zipCodeTF.getText();
        
        user.setfirstName(firstName);
        user.setlastName(lastName);
        user.setEmail(email);
        user.setphoneNumber(phoneNumIn);
        user.setaddress(address);
        user.setcity(city);
        user.setzipCode(zipCode);
        
        try
        {
            ForInsertUser forInsertUser = new ForInsertUser(user);
        }
        catch (SQLException ex)
        {
            Logger.getLogger(UserInfo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_RegisterButtonMouseClicked

    private void alreadyMemberLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_alreadyMemberLabelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_alreadyMemberLabelMouseClicked

    private void alreadyMemberLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_alreadyMemberLabelMouseEntered
        // TODO add your handling code here:
        alreadyMemberLabel.setFont(new java.awt.Font("Tsukushi A Round Gothic", 2, 12)); // NOI18N
    }//GEN-LAST:event_alreadyMemberLabelMouseEntered

    private void alreadyMemberLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_alreadyMemberLabelMouseExited
        // TODO add your handling code here:
        alreadyMemberLabel.setFont(new java.awt.Font("Tsukushi A Round Gothic", 0, 12));
    }//GEN-LAST:event_alreadyMemberLabelMouseExited

    public void ShowShoppingCart(Price price){
        
        BlueSyoPriceLabel.setText("$" + Integer.toString(price.getSyo()));
        BlueChikuPriceLabel.setText("$" + Integer.toString(price.getChiku()));
        BlueBaiPriceLabel.setText("$" + Integer.toString(price.getBai()));
        int allSum = price.getSyo() + price.getChiku() + price.getBai();
        PriceLabel.setText("$" + Integer.toString(allSum));
        
    }
    
    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserInfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AddressLabel;
    private javax.swing.JTextField AddressTF;
    private javax.swing.JLabel BlueBaiLabel;
    private javax.swing.JLabel BlueBaiPriceLabel;
    private javax.swing.JLabel BlueChikuLabel;
    private javax.swing.JLabel BlueChikuPriceLabel;
    private javax.swing.JPanel BluePanel;
    private javax.swing.JLabel BlueSyoLabel;
    private javax.swing.JLabel BlueSyoPriceLabel;
    private javax.swing.JLabel EmailLabel;
    private javax.swing.JTextField EmailTF;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JLabel PaymentPageLabel;
    private javax.swing.JTextField PhoneNumTF;
    private javax.swing.JLabel PriceLabel;
    private javax.swing.JButton RegisterButton;
    private javax.swing.JLabel ShoppingCartLabel;
    private javax.swing.JLabel SushiPageLabel;
    private javax.swing.JLabel TotalLabel;
    private javax.swing.JLabel UserInfoPageLabel;
    private javax.swing.JLabel alreadyMemberLabel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel cityLabel;
    private javax.swing.JTextField cityTF;
    private javax.swing.JLabel firstNameLabel;
    private javax.swing.JTextField firstNameTF;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lastNameLabel;
    private javax.swing.JTextField lastNameTF;
    private javax.swing.JLabel phoneNumLabel;
    private javax.swing.JLabel zipCodeLabel;
    private javax.swing.JTextField zipCodeTF;
    // End of variables declaration//GEN-END:variables

}
