/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package assignment3_order;

/**
 *
 * @author senafunakubo
 */
public class UserInfo extends javax.swing.JFrame {

    /** Creates new form UserInfo */
    public UserInfo() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new javax.swing.JPanel();
        SushiPageLabel = new javax.swing.JLabel();
        UserInfoPageLabel = new javax.swing.JLabel();
        PaymentPageLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        BluePanel = new javax.swing.JPanel();
        TotalLabel = new javax.swing.JLabel();
        PriceLabel = new javax.swing.JLabel();
        BlueChikuLabel = new javax.swing.JLabel();
        BlueSyoLabel = new javax.swing.JLabel();
        BlueBaiLabel = new javax.swing.JLabel();
        BlueSyoPriceLabel = new javax.swing.JLabel();
        BlueChikuPriceLabel = new javax.swing.JLabel();
        BlueBaiPriceLabel = new javax.swing.JLabel();
        ShoppingCartLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MainPanel.setBackground(new java.awt.Color(251, 251, 251));

        SushiPageLabel.setFont(new java.awt.Font("Tsukushi B Round Gothic", 2, 14)); // NOI18N
        SushiPageLabel.setForeground(new java.awt.Color(204, 204, 204));
        SushiPageLabel.setText("Sushi");
        SushiPageLabel.setPreferredSize(new java.awt.Dimension(34, 24));
        SushiPageLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SushiPageLabelMouseClicked(evt);
            }
        });

        UserInfoPageLabel.setFont(new java.awt.Font("Tsukushi B Round Gothic", 0, 14)); // NOI18N
        UserInfoPageLabel.setForeground(new java.awt.Color(51, 51, 51));
        UserInfoPageLabel.setText("UserInfo");
        UserInfoPageLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UserInfoPageLabelMouseClicked(evt);
            }
        });

        PaymentPageLabel.setFont(new java.awt.Font("Tsukushi B Round Gothic", 0, 14)); // NOI18N
        PaymentPageLabel.setForeground(new java.awt.Color(204, 204, 204));
        PaymentPageLabel.setText("Payment");
        PaymentPageLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PaymentPageLabelMouseClicked(evt);
            }
        });

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator1.setForeground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout MainPanelLayout = new javax.swing.GroupLayout(MainPanel);
        MainPanel.setLayout(MainPanelLayout);
        MainPanelLayout.setHorizontalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addComponent(SushiPageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(176, 176, 176)
                        .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(UserInfoPageLabel)
                            .addGroup(MainPanelLayout.createSequentialGroup()
                                .addGap(213, 213, 213)
                                .addComponent(PaymentPageLabel)))
                        .addGap(94, 94, 94))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 573, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        MainPanelLayout.setVerticalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(UserInfoPageLabel)
                    .addComponent(SushiPageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PaymentPageLabel))
                .addGap(0, 0, 0)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        BluePanel.setBackground(new java.awt.Color(0, 153, 153));
        BluePanel.setForeground(new java.awt.Color(59, 175, 235));

        TotalLabel.setFont(new java.awt.Font("Tsukushi A Round Gothic", 1, 10)); // NOI18N
        TotalLabel.setForeground(new java.awt.Color(255, 255, 255));
        TotalLabel.setText("Total");

        PriceLabel.setFont(new java.awt.Font("Tsukushi A Round Gothic", 1, 10)); // NOI18N
        PriceLabel.setForeground(new java.awt.Color(255, 255, 255));
        PriceLabel.setText("$0");

        BlueChikuLabel.setFont(new java.awt.Font("Tsukushi A Round Gothic", 0, 10)); // NOI18N
        BlueChikuLabel.setForeground(new java.awt.Color(255, 255, 255));
        BlueChikuLabel.setText("Chiku");

        BlueSyoLabel.setFont(new java.awt.Font("Tsukushi A Round Gothic", 0, 10)); // NOI18N
        BlueSyoLabel.setForeground(new java.awt.Color(255, 255, 255));
        BlueSyoLabel.setText("Syo");

        BlueBaiLabel.setFont(new java.awt.Font("Tsukushi A Round Gothic", 0, 10)); // NOI18N
        BlueBaiLabel.setForeground(new java.awt.Color(255, 255, 255));
        BlueBaiLabel.setText("Bai");

        BlueSyoPriceLabel.setFont(new java.awt.Font("Tsukushi A Round Gothic", 0, 10)); // NOI18N
        BlueSyoPriceLabel.setForeground(new java.awt.Color(255, 255, 255));
        BlueSyoPriceLabel.setText("$0");

        BlueChikuPriceLabel.setFont(new java.awt.Font("Tsukushi A Round Gothic", 0, 10)); // NOI18N
        BlueChikuPriceLabel.setForeground(new java.awt.Color(255, 255, 255));
        BlueChikuPriceLabel.setText("$0");

        BlueBaiPriceLabel.setFont(new java.awt.Font("Tsukushi A Round Gothic", 0, 10)); // NOI18N
        BlueBaiPriceLabel.setForeground(new java.awt.Color(255, 255, 255));
        BlueBaiPriceLabel.setText("$0");

        ShoppingCartLabel.setFont(new java.awt.Font("Tsukushi B Round Gothic", 0, 14)); // NOI18N
        ShoppingCartLabel.setForeground(new java.awt.Color(255, 255, 255));
        ShoppingCartLabel.setText("Shopping Cart");

        javax.swing.GroupLayout BluePanelLayout = new javax.swing.GroupLayout(BluePanel);
        BluePanel.setLayout(BluePanelLayout);
        BluePanelLayout.setHorizontalGroup(
            BluePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BluePanelLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(BluePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ShoppingCartLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BluePanelLayout.createSequentialGroup()
                        .addGroup(BluePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(BluePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BluePanelLayout.createSequentialGroup()
                                    .addComponent(BlueSyoLabel)
                                    .addGap(12, 12, 12))
                                .addComponent(BlueChikuLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BluePanelLayout.createSequentialGroup()
                                    .addComponent(BlueBaiLabel)
                                    .addGap(14, 14, 14)))
                            .addComponent(TotalLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(BluePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BlueSyoPriceLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(BlueChikuPriceLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(BlueBaiPriceLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(PriceLabel, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGap(45, 45, 45))
        );
        BluePanelLayout.setVerticalGroup(
            BluePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BluePanelLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(ShoppingCartLabel)
                .addGap(52, 52, 52)
                .addGroup(BluePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BlueSyoLabel)
                    .addComponent(BlueSyoPriceLabel))
                .addGap(18, 18, 18)
                .addGroup(BluePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BlueChikuLabel)
                    .addComponent(BlueChikuPriceLabel))
                .addGap(18, 18, 18)
                .addGroup(BluePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BlueBaiLabel)
                    .addComponent(BlueBaiPriceLabel))
                .addGap(99, 99, 99)
                .addGroup(BluePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PriceLabel)
                    .addComponent(TotalLabel))
                .addContainerGap(135, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(BluePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BluePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(MainPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SushiPageLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SushiPageLabelMouseClicked
        // TODO add your handling code here:
        SushiPageLabel.setForeground(java.awt.Color.BLACK);
        UserInfoPageLabel.setForeground(java.awt.Color.lightGray);
        PaymentPageLabel.setForeground(java.awt.Color.lightGray);
    }//GEN-LAST:event_SushiPageLabelMouseClicked

    private void UserInfoPageLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UserInfoPageLabelMouseClicked
        // TODO add your handling code here:
        UserInfoPageLabel.setForeground(java.awt.Color.BLACK);
        SushiPageLabel.setForeground(java.awt.Color.lightGray);
        PaymentPageLabel.setForeground(java.awt.Color.lightGray);
    }//GEN-LAST:event_UserInfoPageLabelMouseClicked

    private void PaymentPageLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PaymentPageLabelMouseClicked
        // TODO add your handling code here:
        PaymentPageLabel.setForeground(java.awt.Color.BLACK);
        SushiPageLabel.setForeground(java.awt.Color.lightGray);
        UserInfoPageLabel.setForeground(java.awt.Color.lightGray);
    }//GEN-LAST:event_PaymentPageLabelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserInfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BlueBaiLabel;
    private javax.swing.JLabel BlueBaiPriceLabel;
    private javax.swing.JLabel BlueChikuLabel;
    private javax.swing.JLabel BlueChikuPriceLabel;
    private javax.swing.JPanel BluePanel;
    private javax.swing.JLabel BlueSyoLabel;
    private javax.swing.JLabel BlueSyoPriceLabel;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JLabel PaymentPageLabel;
    private javax.swing.JLabel PriceLabel;
    private javax.swing.JLabel ShoppingCartLabel;
    private javax.swing.JLabel SushiPageLabel;
    private javax.swing.JLabel TotalLabel;
    private javax.swing.JLabel UserInfoPageLabel;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables

}
